---

constants:
  filename: "your_schedules.json"
  version: "reborn"

# Feel free to change the values Below here to suit your wants
variables:
  username: "User"
  # Voice is the voice to use when speaking messages. 1 is female, 0 is Male
  voice: 1
  # The icon of the notifications. Let it be an absolute path
  app_icon: "./logo.ico"
  
...